apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.github.kanedafromparis/fun: yes
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: ${project.artifactId}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1200
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - image: ${quarkus.container-image.registry}/${user.name}/${project.artifactId}:${project.version}
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath:
                    metadata.name
            - name: TESTING_ENV
              value: test

          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          resources:
            requests:
              cpu: 200m
              memory: 256M
            limits:
              cpu: 2
              memory: 512M
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
          readinessProbe:
              httpGet:
                path: /ready
                port: 8080
                httpHeaders:
                  - name: Custom-Header
                    value: Awesome
              initialDelaySeconds: 3
              periodSeconds: 3
              failureThreshold: 2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp-volume
          emptyDir: {}
